I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/ddm_room.rpy", line 18, in script
    if "intro" not in player["enzo"]:
  File "game/ddm_room.rpy", line 18, in <module>
    if "intro" not in player["enzo"]:
KeyError: 'enzo'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/ddm_room.rpy", line 18, in script
    if "intro" not in player["enzo"]:
  File "E:\RenPy\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "E:\RenPy\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "E:\RenPy\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/ddm_room.rpy", line 18, in <module>
    if "intro" not in player["enzo"]:
KeyError: 'enzo'

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Project Play 0.1
Tue Dec 20 20:33:51 2022
