I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/ddm_room.rpy", line 2, in script
    scene ddm placeholder
Exception: Image 'ddm' does not accept attributes 'placeholder'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/ddm_room.rpy", line 2, in script
    scene ddm placeholder
  File "E:\RenPy\renpy-8.0.3-sdk\renpy\ast.py", line 1542, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "E:\RenPy\renpy-8.0.3-sdk\renpy\ast.py", line 1371, in show_imspec
    renpy.config.show(name,
  File "E:\RenPy\renpy-8.0.3-sdk\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "E:\RenPy\renpy-8.0.3-sdk\renpy\display\image.py", line 414, in find_target
    self.target = target._duplicate(a)
  File "E:\RenPy\renpy-8.0.3-sdk\renpy\display\core.py", line 397, in _duplicate
    args.extraneous()
  File "E:\RenPy\renpy-8.0.3-sdk\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'ddm' does not accept attributes 'placeholder'.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Project Play 0.1
Tue Dec 20 15:04:28 2022
